# Generated by Django 4.2.4 on 2023-09-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=10000, verbose_name='стоимость курса'),
        ),
    ]
