# Generated by Django 4.2.4 on 2023-09-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.PositiveIntegerField(choices=[('cash', 'cash'), ('transfer', 'transfer')], default='transfer', verbose_name='Сумма оплаты'),
        ),
    ]
