# Generated by Django 4.2.4 on 2023-09-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_alter_payment_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id платежа stripe'),
        ),
    ]
