# Generated by Django 4.2.4 on 2023-09-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_remove_payment_stripe_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('transfer', 'Перевод на счет')], max_length=100, null=True, verbose_name='Способ оплаты'),
        ),
    ]
