# Generated by Django 4.2.4 on 2023-09-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_payment_is_paid_payment_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время обновления'),
        ),
    ]
